exclude: ^.*/vendor/.*|.*\.svg$
minimum_pre_commit_version: "1.17.0"
repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v1.23.0"
    hooks:
      - id: "commitizen"
        language_version: "python3.8"
        stages: ["commit-msg"]

  - repo: "https://github.com/prettier/prettier"
    rev: "2.0.5"
    hooks:
      - id: "prettier"
        name: "Format UI code (prettier)"
        exclude: ^\.github/.*|.*/templates/.*$

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v3.1.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"

  - repo: "https://github.com/pre-commit/mirrors-eslint"
    rev: "v7.4.0"
    hooks:
      - id: "eslint"
        name: "Lint UI code (eslint)"
        args: ["--fix"]
        additional_dependencies:
          - "babel-eslint@10.1.0"
          - "eslint@7.4.0"
          - "eslint-config-prettier@6.11.0"
          - "eslint-config-standard@14.1.1"
          - "eslint-plugin-import@2.22.0"
          - "eslint-plugin-node@11.1.0"
          - "eslint-plugin-prettier@3.1.4"
          - "eslint-plugin-promise@4.2.1"
          - "eslint-plugin-react@7.20.3"
          - "eslint-plugin-react-hooks@4.0.8"
          - "eslint-plugin-standard@4.0.1"
          - "prettier@2.0.5"
